language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: GqFlJvvnf+LaSSqoZsgIe+rEHsVjDF+gAnsjHUEECNcsLKQYHiiYpsHCrc7xLUh9Rc4E+smioTBIETyOawNSY8sOe09BKgmTLHSixpr2A2FXAif5KYUZ2mfx7/WFpZNTuvjkGRPbsLjCwezjvX+KpNxcVD9VyZYaNjZFIZ+OiWkhF/5sxUg0ORbzeBQXvoP5uBHfhmWC31kVl0dvLreUbk277F2Auq3TltBeq6X7Uupb6y5rBeFhTbtt9/k5Z+uuP5nhL+ekgSgusubc4tfmnqP8DnraSx0NXH1jCkvLRRJ7RYA2TnOLYMm7VZeWpA4170hc13eNNE+tDoNUYlX0EiK9cjk3+VpjhYiME3pnBvCCg1/f1y57+36GSAHLwDcd8eesKf41SYKgEsi1ryHjKSECDOCpf+gw8bPIzded4oUPmNIkv81VHs08LOk67Lm3o4Yf8RlkWX82OeBfNv4HeVu2emU5zgf8TQztcfiBYxENrdm//wiBk2y14jHKgCiEtJc4NnS74MdueHeT+9B61e3Qn/wrac4UaftjYb/wcHImix8ISQ02PB6dkCz+vCd5h7cPgt32JJrLcvcd0F2Cd84k8fLspRvLpuKMZtgi08cnNlFP0L0Q5GJPezpZXzJMnUPNpUeK/+MbJ9q0GT7EsNhIgY2sk/bHgJUNhPPwcx4=
  app: intense-temple-20361
  on:
    repo: namninja/node-restaurants-app-mongoose
